//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaEntity_2015
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS
    {
        public STATUS()
        {
            this.REL_TICKET_HAS_STATUS = new HashSet<REL_TICKET_HAS_STATUS>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string color { get; set; }
    
        public virtual ICollection<REL_TICKET_HAS_STATUS> REL_TICKET_HAS_STATUS { get; set; }
    }
}
